[2023-05-10 13:16:37,068 cloud_run.py._kwargs_from_flask_request:154]ERROR: Could not create kwargs from request <<Request 'http://yaas-scheduler-zhyr3huy4a-ey.a.run.app/command' [POST]>> using <async_kwargs_fn>. Error: Could not extract <Config> from JSON content: <b'{\n    "calendar_config": {\n        "type": "google_caldav",\n        "calendar_id": "ajbefo4rt4j8mtd808pi4gi5uc@group.calendar.google.com",\n        "username": "ds.env.poc.error@gmail.com",\n        "secret_name": "projects/245814988234/secrets/yaas_calendar_credentials/versions/latest"\n    },\n    "cache_config": {\n        "type": "gcs_sqlite",\n        "bucket_name": "yaas-app-245814988234",\n        "object_path": "yaas/calendar_cache.sql"\n    },\n    "topic_to_pubsub_gcs": "gs://yaas-app-245814988234/yaas/topic_to_pubsub",\n    "topic_to_pubsub": {\n        "standard": "projects/yaas-372309/topics/yaas-enact-standard-request",\n        "yaas": "projects/yaas-372309/topics/yaas-enact-standard-request"\n    }\n}\n'>. Error: Could not instantiate <Config> from kwargs <{'calendar_config': None, 'cache_config': GcsCacheConfig(type='gcs_sqlite', bucket_name='yaas-app-245814988234', object_path='yaas/calendar_cache.sql'), 'topic_to_pubsub': {'standard': 'projects/yaas-372309/topics/yaas-enact-standard-request', 'yaas': 'projects/yaas-372309/topics/yaas-enact-standard-request'}, 'topic_to_pubsub_gcs': 'gs://yaas-app-245814988234/yaas/topic_to_pubsub', 'retention_config': None}>. Error: ("'calendar_config' must be <class 'yaas_config.config.CalendarCacheConfig'> (got None that is a <class 'NoneType'>).", Attribute(name='calendar_config', default=NOTHING, validator=<instance_of validator for type <class 'yaas_config.config.CalendarCacheConfig'>>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'yaas_config.config.CalendarCacheConfig'>, converter=None, kw_only=True, inherited=False, on_setattr=None, alias='calendar_config'), <class 'yaas_config.config.CalendarCacheConfig'>, None)|'Traceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/yaas_common/dto_defaults.py", line 175, in from_dict\n    result = cls(**kwargs)\n             ^^^^^^^^^^^^^\n  File "<attrs generated init yaas_config.config.Config>", line 9, in __init__\n    __attr_validator_calendar_config(self, __attr_calendar_config, self.calendar_config)\n  File "/usr/local/lib/python3.11/site-packages/attr/validators.py", line 105, in __call__\n    raise TypeError(\nTypeError: ("\'calendar_config\' must be <class \'yaas_config.config.CalendarCacheConfig\'> (got None that is a <class \'NoneType\'>).", Attribute(name=\'calendar_config\', default=NOTHING, validator=<instance_of validator for type <class \'yaas_config.config.CalendarCacheConfig\'>>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class \'yaas_config.config.CalendarCacheConfig\'>, converter=None, kw_only=True, inherited=False, on_setattr=None, alias=\'calendar_config\'), <class \'yaas_config.config.CalendarCacheConfig\'>, None)\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/yaas_flask/cloud_run.py", line 71, in read_configuration\n    result = config.Config.from_json(config_json)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yaas_common/dto_defaults.py", line 244, in from_json\n    return cls.from_dict(value)\n           ^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yaas_common/dto_defaults.py", line 177, in from_dict\n    raise ValueError(f"Could not instantiate <{cls.__name__}> from kwargs <{kwargs}>. Error: {err}") from err\nValueError: Could not instantiate <Config> from kwargs <{\'calendar_config\': None, \'cache_config\': GcsCacheConfig(type=\'gcs_sqlite\', bucket_name=\'yaas-app-245814988234\', object_path=\'yaas/calendar_cache.sql\'), \'topic_to_pubsub\': {\'standard\': \'projects/yaas-372309/topics/yaas-enact-standard-request\', \'yaas\': \'projects/yaas-372309/topics/yaas-enact-standard-request\'}, \'topic_to_pubsub_gcs\': \'gs://yaas-app-245814988234/yaas/topic_to_pubsub\', \'retention_config\': None}>. Error: ("\'calendar_config\' must be <class \'yaas_config.config.CalendarCacheConfig\'> (got None that is a <class \'NoneType\'>).", Attribute(name=\'calendar_config\', default=NOTHING, validator=<instance_of validator for type <class \'yaas_config.config.CalendarCacheConfig\'>>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class \'yaas_config.config.CalendarCacheConfig\'>, converter=None, kw_only=True, inherited=False, on_setattr=None, alias=\'calendar_config\'), <class \'yaas_config.config.CalendarCacheConfig\'>, None)\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/yaas_flask/cloud_run.py", line 147, in _kwargs_from_flask_request\n    kwargs = await async_kwargs_fn(flask.request)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yaas_scheduler_service/main.py", line 53, in async_kwargs_fn\n    configuration=cloud_run.read_configuration(),\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/yaas_flask/cloud_run.py", line 73, in read_configuration\n    raise RuntimeError(\nRuntimeError: Could not extract <Config> from JSON content: <b\'{\\n    "calendar_config": {\\n        "type": "google_caldav",\\n        "calendar_id": "ajbefo4rt4j8mtd808pi4gi5uc@group.calendar.google.com",\\n        "username": "ds.env.poc.error@gmail.com",\\n        "secret_name": "projects/245814988234/secrets/yaas_calendar_credentials/versions/latest"\\n    },\\n    "cache_config": {\\n        "type": "gcs_sqlite",\\n        "bucket_name": "yaas-app-245814988234",\\n        "object_path": "yaas/calendar_cache.sql"\\n    },\\n    "topic_to_pubsub_gcs": "gs://yaas-app-245814988234/yaas/topic_to_pubsub",\\n    "topic_to_pubsub": {\\n        "standard": "projects/yaas-372309/topics/yaas-enact-standard-request",\\n        "yaas": "projects/yaas-372309/topics/yaas-enact-standard-request"\\n    }\\n}\\n\'>. Error: Could not instantiate <Config> from kwargs <{\'calendar_config\': None, \'cache_config\': GcsCacheConfig(type=\'gcs_sqlite\', bucket_name=\'yaas-app-245814988234\', object_path=\'yaas/calendar_cache.sql\'), \'topic_to_pubsub\': {\'standard\': \'projects/yaas-372309/topics/yaas-enact-standard-request\', \'yaas\': \'projects/yaas-372309/topics/yaas-enact-standard-request\'}, \'topic_to_pubsub_gcs\': \'gs://yaas-app-245814988234/yaas/topic_to_pubsub\', \'retention_config\': None}>. Error: ("\'calendar_config\' must be <class \'yaas_config.config.CalendarCacheConfig\'> (got None that is a <class \'NoneType\'>).", Attribute(name=\'calendar_config\', default=NOTHING, validator=<instance_of validator for type <class \'yaas_config.config.CalendarCacheConfig\'>>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class \'yaas_config.config.CalendarCacheConfig\'>, converter=None, kw_only=True, inherited=False, on_setattr=None, alias=\'calendar_config\'), <class \'yaas_config.config.CalendarCacheConfig\'>, None)'
